# Generated by Django 5.0.2 on 2024-03-21 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foe', models.CharField(null=True)),
                ('player_score', models.IntegerField(default=0.0)),
                ('foe_score', models.IntegerField(default=0.0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('highest_ball_speed', models.FloatField(default=0.0, null=True)),
                ('nb_of_bounce', models.IntegerField(default=0.0, null=True)),
                ('longest_set', models.IntegerField(default=0.0, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
