# Generated by Django 5.0.2 on 2024-03-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField(default=list)),
                ('players_stats', models.JSONField(default=dict)),
                ('matches', models.JSONField(default=list)),
            ],
        ),
    ]
