version: '3'

services:
  nginix:
    container_name: nginix
    build: /requirement/nginix
    depends_on:
      - adminer
      - redis
      - hugo
    ports:
      -443:443
    volumes:
      -wordpress_data:/var/www/html
    restart: unsless-stopped
    networks:
      - network
  
  mariadb:
    ontainer_name: mariadb
    build: requirement/mariadb
    volumes:
      -mariadb_data:/var/lib/mysql
    network:
     -network
    restart: unsless-stopp
    env_file:
      - .env

  
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      network

