version: '3.5'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /home/vboxuser/data/wordpress
      o: bind
      type: none
  mariadb:
    driver: local
    driver_opts:
      device: /home/vboxuser/data/mariadb
      o: bind
      type: none

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    #command: ["./wait-for-it.sh", "mariadb:3306", "--", "apache2-foreground"]
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env    
    restart: always