# Generated by Django 5.0.2 on 2024-03-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud_user', '0001_initial'),
        ('pong_game', '0002_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pong_game.tournament'),
        ),
    ]
